snowflake-dagster:
  outputs:
    dev:
      account: IYTNLTJ-MWB17343
      authenticator: externalbrowser
      database: pc_dbt_db
      role: pc_dbt_role
      schema: prod
      threads: 4
      type: snowflake
      user: horace@artemisanalytics.xyz
      warehouse: analytics_xl
  target: dev
