---
repos:
  - repo: local
    hooks:
      - id: sqlfmt
        name: sqlfmt
        entry: sqlfmt
        language: python
        args: [--single-process, --dialect, snowflake]
        require_serial: true
        types_or: [sql, jinja]
