# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: "artemis_dbt"
version: "1.0.0"
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: "snowflake-dagster"

# These configurations specify where dbt should look for different types of files.
# The `source-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["./models"]
analysis-paths: ["./analyses"]
test-paths: ["./tests"]
seed-paths: ["./seeds"]
macro-paths: ["./macros"]
snapshot-paths: ["./snapshots"]

target-path: "target" # directory which will store compiled SQL files
clean-targets: # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

# In this example config, we tell dbt to build all models in the example/ directory
# as tables. These settings can be overridden in the individual model files
# using the `{{ config(...) }}` macro.
models:
  artemis_dbt:
    metrics:
      contracts:
        +snowflake_warehouse: "DAILY_L1"
      defillama:
        +snowflake_warehouse: "DAILY_DEFILLAMA"
    bam_models:
      +snowflake_warehouse: "DAILY_BAM"
    staging:
      aave:
        +snowflake_warehouse: "AAVE"
      acala:
        +snowflake_warehouse: "ACALA"
      aptos:
        +snowflake_warehouse: "APTOS"
      avalanche:
        +snowflake_warehouse: "AVALANCHE"
      axelar:
        +snowflake_warehouse: "AXELAR"
      benqi:
        +snowflake_warehouse: "BENQI_FINANCE"
      bitcoin:
        +snowflake_warehouse: "BITCOIN"
      cardano:
        +snowflake_warehouse: "CARDANO"
      celo:
        +snowflake_warehouse: "CELO"
      compound:
        +snowflake_warehouse: "COMPOUND"
      cosmoshub:
        +snowflake_warehouse: "COSMOSHUB"
      curve:
        +snowflake_warehouse: "CURVE"
      gnosis:
        +snowflake_warehouse: "GNOSIS"
      linea:
        +snowflake_warehouse: "LINEA"
      multiversx:
        +snowflake_warehouse: "MULTIVERSX"
      radiant:
        +snowflake_warehouse: "RADIANT"
      sonne:
        +snowflake_warehouse: "SONNE_FINANCE"
      spark:
        +snowflake_warehouse: "SPARK"
      sushiswap:
        +snowflake_warehouse: "SUSHISWAP_SM"
      trader_joe:
        +snowflake_warehouse: "TRADER_JOE"
      uniswap:
        +snowflake_warehouse: "UNISWAP_TVL_SM"
      uwulend:
        +snowflake_warehouse: "UWULEND"
      venus:
        +snowflake_warehouse: "VENUS"
      zcash:
        +snowflake_warehouse: "ZCASH"
      zksync:
        +snowflake_warehouse: "ZKSYNC"
      zora:
        +snowflake_warehouse: "ZORA"

vars:
  dbt_date:time_zone: "Etc/UTC"
