# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: "artemis_dbt"
version: "1.0.0"
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: "snowflake-dagster"

# These configurations specify where dbt should look for different types of files.
# The `source-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["./models"]
analysis-paths: ["./analyses"]
test-paths: ["./tests"]
seed-paths: ["./seeds"]
macro-paths: ["./macros"]
snapshot-paths: ["./snapshots"]

target-path: "target" # directory which will store compiled SQL files
clean-targets: # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

# In this example config, we tell dbt to build all models in the example/ directory
# as tables. These settings can be overridden in the individual model files
# using the `{{ config(...) }}` macro.
models:
  artemis_dbt:
    metrics:
      contracts:
        +snowflake_warehouse: "DAILY_L1"
      defillama:
        +snowflake_warehouse: "DAILY_DEFILLAMA"
    bam_models:
      +snowflake_warehouse: "DAILY_BAM"
    staging:
      acala:
        +snowflake_warehouse: "ACALA"
      across:
        +snowflake_warehouse: "ACROSS"
      akash:
        +snowflake_warehouse: "AKASH"
      aptos:
        +snowflake_warehouse: "APTOS"
      arbitrum:
        +snowflake_warehouse: "ARBITRUM"
      avalanche:
        +snowflake_warehouse: "AVALANCHE"
      axelar:
        +snowflake_warehouse: "AXELAR"
      base:
        +snowflake_warehouse: "BASE"
      beam:
        +snowflake_warehouse: "BEAM"
      benqi:
        +snowflake_warehouse: "BENQI_FINANCE"
      bitcoin:
        +snowflake_warehouse: "BITCOIN"
      blast:
        +snowflake_warehouse: "BLAST"
      cardano:
        +snowflake_warehouse: "CARDANO"
      cctp:
        +snowflake_warehouse: "CCTP"
      celestia:
        +snowflake_warehouse: "CELESTIA"
      celo:
        +snowflake_warehouse: "CELO"
      coinbase:
        +snowflake_warehouse: "COINBASE"
      compound:
        +snowflake_warehouse: "COMPOUND"
      cosmoshub:
        +snowflake_warehouse: "COSMOSHUB"
      curve:
        +snowflake_warehouse: "CURVE"
      dexalot:
        +snowflake_warehouse: "DEXALOT"
      dfk:
        +snowflake_warehouse: "DFK"
      ethereum:
        +snowflake_warehouse: "ETHEREUM"
      fantom:
        +snowflake_warehouse: "FANTOM"
      flow:
        +snowflake_warehouse: "FLOW"
      frax:
        +snowflake_warehouse: "FRAX"
      fuse:
        +snowflake_warehouse: "FUSE"
      gnosis:
        +snowflake_warehouse: "GNOSIS"
      immutable_x:
        +snowflake_warehouse: "IMMUTABLE_X"
      injective:
        +snowflake_warehouse: "INJECTIVE"
      lido:
        +snowflake_warehouse: "LIDO"
      linea:
        +snowflake_warehouse: "LINEA"
      mantle:
        +snowflake_warehouse: "mantle"
      moonwell:
        +snowflake_warehouse: "MOONWELL"
      multiversx:
        +snowflake_warehouse: "MULTIVERSX"
      optimism:
        +snowflake_warehouse: "OPTIMISM"
      osmosis:
        +snowflake_warehouse: "OSMOSIS"
      pancakeswap:
        +snowflake_warehouse: "PANCAKESWAP_SM"
      polkadot:
        +snowflake_warehouse: "POLKADOT"
      polygon:
        +snowflake_warehouse: "POLYGON"
      near:
        +snowflake_warehouse: "NEAR"
      quickswap:
        +snowflake_warehouse: "QUICKSWAP"
      radiant:
        +snowflake_warehouse: "RADIANT"
      rainbow_bridge:
        +snowflake_warehouse: "RAINBOW_BRIDGE"
      rocketpool:
        +snowflake_warehouse: "ROCKETPOOL"
      scroll:
        +snowflake_warehouse: "SCROLL"
      seamless:
        +snowflake_warehouse: "SEAMLESSPROTOCOL"
      sei:
        +snowflake_warehouse: "SEI"
      solana:
        +snowflake_warehouse: "SOLANA"
      sonne:
        +snowflake_warehouse: "SONNE_FINANCE"
      spark:
        +snowflake_warehouse: "SPARK"
      stacks:
        +snowflake_warehouse: "STACKS"
      stader:
        +snowflake_warehouse: "STADER"
      stakewise:
        +snowflake_warehouse: "STAKEWISE"
      stride:
        +snowflake_warehouse: "STRIDE"
      sushiswap:
        +snowflake_warehouse: "SUSHISWAP_SM"
      ton:
        +snowflake_warehouse: "TON"
      trader_joe:
        +snowflake_warehouse: "TRADER_JOE"
      tron:
        +snowflake_warehouse: "TRON"
      uniswap:
        +snowflake_warehouse: "UNISWAP_SM"
      uwu_lend:
        +snowflake_warehouse: "UWULEND"
      venus:
        +snowflake_warehouse: "VENUS"
      zcash:
        +snowflake_warehouse: "ZCASH"
      zksync:
        +snowflake_warehouse: "ZKSYNC"
      zora:
        +snowflake_warehouse: "ZORA"

vars:
  dbt_date:time_zone: "Etc/UTC"
