snowflake-dagster:
  outputs:
    dev:
      account: IYTNLTJ-MWB17343
      authenticator: externalbrowser
      database: PC_DBT_DB
      role: PC_DBT_ROLE
      schema: PROD
      threads: 4
      type: snowflake
      user: irwyn@artemisanalytics.xyz
      warehouse: MEDIUM
  target: dev
