{{ config(materialized="table", snowflake_warehouse="DAILY_BAM") }}

select
    LOWER(contract_address) AS contract_address,
    date,
    name,
    null as symbol,
    app as namespace,
    friendly_name,
    category,
    gas as total_gas,
    gas_usd as total_gas_usd,
    txns as transactions,
    dau,
    real_users,
    null as avg_gas_per_address,
    null as avg_gas_usd_per_address,
    null as rev,
    null as rev_usd,
    null as token_transfer_usd,
    null as token_transfer,
    null as avg_token_price,
    null as mau,
    'arbitrum' as chain
from {{ ref("ez_arbitrum_metrics_by_contract_v2") }}
union
select
    LOWER(contract_address) AS contract_address,
    date,
    name,
    null as symbol,
    app as namespace,
    friendly_name,
    category,
    gas as total_gas,
    gas_usd as total_gas_usd,
    txns as transactions,
    dau,
    real_users,
    null as avg_gas_per_address,
    null as avg_gas_usd_per_address,
    null as rev,
    null as rev_usd,
    null as token_transfer_usd,
    null as token_transfer,
    null as avg_token_price,
    null as mau,
    'avalanche' as chain
from {{ ref("ez_avalanche_metrics_by_contract_v2") }}
union
select
    LOWER(contract_address) AS contract_address,
    date,
    name,
    null as symbol,
    app as namespace,
    friendly_name,
    category,
    gas as total_gas,
    gas_usd as total_gas_usd,
    txns as transactions,
    dau,
    real_users,
    null as avg_gas_per_address,
    null as avg_gas_usd_per_address,
    null as rev,
    null as rev_usd,
    null as token_transfer_usd,
    null as token_transfer,
    null as avg_token_price,
    null as mau,
    'base' as chain
from {{ ref("ez_base_metrics_by_contract_v2") }}
union
select
    LOWER(contract_address) AS contract_address,
    date,
    name,
    null as symbol,
    app as namespace,
    friendly_name,
    category,
    gas as total_gas,
    gas_usd as total_gas_usd,
    txns as transactions,
    dau,
    real_users,
    null as avg_gas_per_address,
    null as avg_gas_usd_per_address,
    null as rev,
    null as rev_usd,
    null as token_transfer_usd,
    null as token_transfer,
    null as avg_token_price,
    null as mau,
    'bsc' as chain
from {{ ref("ez_bsc_metrics_by_contract_v2") }}
union
select
    LOWER(contract_address) AS contract_address,
    date,
    name,
    null as symbol,
    app as namespace,
    friendly_name,
    category,
    gas as total_gas,
    gas_usd as total_gas_usd,
    txns as transactions,
    dau,
    real_users,
    null as avg_gas_per_address,
    null as avg_gas_usd_per_address,
    null as rev,
    null as rev_usd,
    null as token_transfer_usd,
    null as token_transfer,
    null as avg_token_price,
    null as mau,
    'ethereum' as chain
from {{ ref("ez_ethereum_metrics_by_contract_v2") }}
union
select
    LOWER(contract_address) AS contract_address,
    date,
    name,
    null as symbol,
    app as namespace,
    friendly_name,
    category,
    gas as total_gas,
    gas_usd as total_gas_usd,
    txns as transactions,
    dau,
    real_users,
    null as avg_gas_per_address,
    null as avg_gas_usd_per_address,
    null as rev,
    null as rev_usd,
    null as token_transfer_usd,
    null as token_transfer,
    null as avg_token_price,
    null as mau,
    'optimism' as chain
from {{ ref("ez_optimism_metrics_by_contract_v2") }}
union
select
    LOWER(contract_address) AS contract_address,
    date,
    name,
    null as symbol,
    app as namespace,
    friendly_name,
    category,
    gas as total_gas,
    gas_usd as total_gas_usd,
    txns as transactions,
    dau,
    real_users,
    null as avg_gas_per_address,
    null as avg_gas_usd_per_address,
    null as rev,
    null as rev_usd,
    null as token_transfer_usd,
    null as token_transfer,
    null as avg_token_price,
    null as mau,
    'polygon' as chain
from {{ ref("ez_polygon_metrics_by_contract_v2") }}
union
select
    contract_address,
    date,
    name,
    null as symbol,
    app as namespace,
    friendly_name,
    category,
    gas as total_gas,
    gas_usd as total_gas_usd,
    txns as transactions,
    dau,
    real_users,
    null as avg_gas_per_address,
    null as avg_gas_usd_per_address,
    null as rev,
    null as rev_usd,
    null as token_transfer_usd,
    null as token_transfer,
    null as avg_token_price,
    null as mau,
    'near' as chain
from {{ ref("ez_near_metrics_by_contract_v2") }}
union
select
    contract_address,
    date,
    name,
    null as symbol,
    app as namespace,
    friendly_name,
    category,
    gas as total_gas,
    gas_usd as total_gas_usd,
    txns as transactions,
    dau,
    real_users,
    null as avg_gas_per_address,
    null as avg_gas_usd_per_address,
    null as rev,
    null as rev_usd,
    null as token_transfer_usd,
    null as token_transfer,
    null as avg_token_price,
    null as mau,
    'sei' as chain
from {{ ref("ez_sei_metrics_by_contract_v2") }}
union
select
    contract_address,
    date,
    name,
    null as symbol,
    app as namespace,
    friendly_name,
    category,
    gas as total_gas,
    gas_usd as total_gas_usd,
    txns as transactions,
    dau,
    real_users,
    null as avg_gas_per_address,
    null as avg_gas_usd_per_address,
    null as rev,
    null as rev_usd,
    null as token_transfer_usd,
    null as token_transfer,
    null as avg_token_price,
    null as mau,
    'tron' as chain
from {{ ref("ez_tron_metrics_by_contract_v2") }}
union
select
    LOWER(contract_address) AS contract_address,
    date,
    name,
    null as symbol,
    app as namespace,
    friendly_name,
    category,
    gas as total_gas,
    gas_usd as total_gas_usd,
    txns as transactions,
    dau,
    real_users,
    null as avg_gas_per_address,
    null as avg_gas_usd_per_address,
    null as rev,
    null as rev_usd,
    null as token_transfer_usd,
    null as token_transfer,
    null as avg_token_price,
    null as mau,
    'mantle' as chain
from {{ ref("ez_mantle_metrics_by_contract_v2") }}
union
select
    contract_address,
    date,
    name::string as name,
    null as symbol,
    app::string as namespace,
    friendly_name::string as friendly_name,
    category::string as category,
    gas as total_gas,
    gas_usd as total_gas_usd,
    txns as transactions,
    dau,
    real_users,
    null as avg_gas_per_address,
    null as avg_gas_usd_per_address,
    null as rev,
    null as rev_usd,
    null as token_transfer_usd,
    null as token_transfer,
    null as avg_token_price,
    null as mau,
    'sui' as chain
from {{ ref("ez_sui_metrics_by_contract_v2") }}
union
select
    contract_address,
    date,
    name::string as name,
    null as symbol,
    app::string as namespace,
    friendly_name::string as friendly_name,
    category::string as category,
    gas as total_gas,
    gas_usd as total_gas_usd,
    txns as transactions,
    dau,
    real_users,
    null as avg_gas_per_address,
    null as avg_gas_usd_per_address,
    null as rev,
    null as rev_usd,
    null as token_transfer_usd,
    null as token_transfer,
    null as avg_token_price,
    null as mau,
    'injective' as chain
from {{ ref("ez_injective_metrics_by_contract_v2") }}
union
select
    contract_address,
    date,
    name::string as name,
    null as symbol,
    app::string as namespace,
    friendly_name::string as friendly_name,
    category::string as category,
    gas as total_gas,
    gas_usd as total_gas_usd,
    txns as transactions,
    dau,
    real_users,
    null as avg_gas_per_address,
    null as avg_gas_usd_per_address,
    null as rev,
    null as rev_usd,
    null as token_transfer_usd,
    null as token_transfer,
    null as avg_token_price,
    null as mau,
    'stellar' as chain
from {{ ref("ez_stellar_metrics_by_contract_v2") }}
union
select
    contract_address,
    date,
    name,
    null as symbol,
    namespace,
    friendly_name,
    category,
    gas as total_gas,
    gas_usd as total_gas_usd,
    txns as transactions,
    dau,
    real_users,
    avg_gas_per_address,
    avg_gas_usd_per_address,
    rev,
    rev_usd,
    null as token_transfer_usd,
    null as token_transfer,
    null as avg_token_price,
    mau,
    'solana' as chain
from {{ ref("ez_solana_metrics_by_contract_v2") }}
union
select
    LOWER(contract_address) AS contract_address,
    date,
    name,
    null as symbol,
    app as namespace,
    friendly_name,
    category,
    gas as total_gas,
    gas_usd as total_gas_usd,
    txns as transactions,
    dau,
    real_users,
    null as avg_gas_per_address,
    null as avg_gas_usd_per_address,
    null as rev,
    null as rev_usd,
    null as token_transfer_usd,
    null as token_transfer,
    null as avg_token_price,
    null as mau,
    'celo' as chain
from {{ ref("ez_celo_metrics_by_contract_v2") }}